apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2019-08-12T12:23:17Z
  generation: 2
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.14.0
    component: controller
    heritage: Tiller
    release: broken-grasshopper
  name: broken-grasshopper-nginx-ingress-controller
  namespace: ingress-basic
  resourceVersion: "27434"
  selfLink: /apis/extensions/v1beta1/namespaces/ingress-basic/deployments/broken-grasshopper-nginx-ingress-controller
  uid: f6c79505-bcfb-11e9-8603-2eb4fa0e67c5
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-ingress
      component: controller
      release: broken-grasshopper
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-ingress
        component: controller
        release: broken-grasshopper
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --default-backend-service=blocbit/blocbit
        - --election-id=ingress-controller-leader
        - --ingress-class=nginx
        - --configmap=ingress-basic/broken-grasshopper-nginx-ingress-controller
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nginx-ingress-controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsUser: 33
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: broken-grasshopper-nginx-ingress
      serviceAccountName: broken-grasshopper-nginx-ingress
      terminationGracePeriodSeconds: 60
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2019-08-12T12:23:36Z
    lastUpdateTime: 2019-08-12T12:23:36Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2