from time import time

from utility.printable import Printable


class Bloc(Printable):
    """A single bloc of our blocchain.

    Attributes:
        :index: The index of this bloc.
        :previous_hash: The hash of the previous bloc in the blocchain.
        :timestamp: The timestamp of the bloc (automatically generated by
        default).
        :submissions: A list of submission which are included in the bloc.
        :proof: The proof of work number that yielded this bloc.
    """

    def __init__(self, index, previous_hash, submissions, proof, time=time()):
        self.index = index
        self.previous_hash = previous_hash
        self.timestamp = time
        self.submissions = submissions
        self.proof = proof
